name: CVHome
main: org.cubeville.cvhome.CVHome
author: unixadmin,ToeMan_
version: 0.2

depend: [CVTools]

commands:
  sethome:
    description: Set a home command
  home:
    description: Teleport to a home command
  homeinfo:
    description: Get information on a home
  homeupdate:
    description: Update player homes with player names.

permissions:
  cvhome.max.1:
    description: Maximum of 1 home.
    default: true
  cvhome.max.2:
    description: Maximum of 2 homes.
    default: op
  cvhome.max.3:
    description: Maximum of 3 homes.
    default: false
  cvhome.max.4:
    description: Maximum of 4 homes.
    default: false
  cvhome.admin.sethome:
    description: Admin override to set homes for any player.
    default: op
  cvhome.admin.teleporthome:
    description: Admin override to teleport to any players' homes.
    default: op
  cvhome.admin.infohome:
    description: Admin override to get a player's home information.
    default: op
  cvhome.admin.updatehome:
    description: Admin override to update player's homes to include player names.
    default: op